More tests for corners of numeric conversions.
google/cel-spec pull request #183
Opened 2021-03-19 03:25 UTC by JimLarson

2021-03-22 20:04 UTC, TristonianJones requested changes

2021-04-03 05:31 UTC, JimLarson commented on tests/simple/testdata/conversions.textproto
> +    value { double_value: 9.007199254740992e15 }
Nice catch. Correct, it's not INT_MAX, it's the maximum contiguous int that a double can represent. Added comments here and for "int_min/max_exact".

2021-04-03 05:38 UTC, JimLarson commented
PTAL

2021-04-07 04:43 UTC, TristonianJones approved these changes

2021-04-08 23:32 UTC, JimLarson commented
Oops, forgot that out of range doubles should be float infinities. Updated tests (they pass in cel-go!). PTAL.

2021-04-14 19:03 UTC, TristonianJones approved these changes

2021-04-18 02:58 UTC, merged