typo, formatting, and link fixes
google/cel-spec pull request #422
Opened 2024-12-12 19:30 UTC by hudlow

2024-12-12 19:30 UTC, hudlow commented on doc/langdef.md
> +     fractional seconds with an 's' suffix
I think "fractional" and "sub-" are redundant. :-)

2025-01-02 17:29 UTC, jnthntatum commented
/gcbrun

2025-01-02 17:50 UTC, jnthntatum requested changes
Thank you!

2025-01-02 17:50 UTC, jnthntatum commented on doc/langdef.md
> +sub-expressions is not guaranteed. If multiple sub-expressions would evaluate to
I know it was inconsistent before your change, but I think unhyphenated "subexpression" is more commonly used. Would you mind updating to that?

2025-01-03 02:20 UTC, hudlow commented on doc/langdef.md
> +sub-expressions is not guaranteed. If multiple sub-expressions would evaluate to
I don't have a strong opinion here, but currently `subexpression` is used in two places and `sub-expression` is used in twenty-one places within this document. Are you sure we should change the other twenty-one places instead?

2025-01-03 18:35 UTC, jnthntatum commented on doc/langdef.md
> +sub-expressions is not guaranteed. If multiple sub-expressions would evaluate to
I'd prefer it, but don't want to hold up your PR over it.

2025-01-03 18:36 UTC, jnthntatum approved these changes

2025-01-03 18:37 UTC, jnthntatum commented
/gcbrun

2025-01-03 19:40 UTC, merged